---
- hosts: all
  become: true
  tasks:
    - ansible.builtin.debug:
        msg: Setup smart home via ansible playbooks

- name: Audio Setup
  ansible.builtin.import_playbook: playbook-audio.yml

- name: Automation
  ansible.builtin.import_playbook: playbook-automation.yml
