---
- hosts: all
  become: true
  vars:
    - dir_download: /home/pi/download

  tasks:
    - name: Install homeassistant dependencies
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-dev
          - python3-venv
          - python3-pip
          - bluez
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7
          - libtiff5
          - libturbojpeg0-dev
          - tzdata

    - name: Install virtualenv via pip
      ansible.builtin.pip:
        name:
          - virtualenv
          - cryptography
        executable: pip3

    - name: Create homeassistant user
      ansible.builtin.user:
        name: homeassistant
        system: true
        groups:
          - root
          - dialout
          - gpio
          - i2c

    - name: Create homeassistant directory
      ansible.builtin.file:
        path: "/srv/homeassistant"
        state: directory
        mode: "0755"
        group: homeassistant
        owner: homeassistant

    - name: Create python venv and install dependencies
      ansible.builtin.pip:
        name:
          - wheel
          - homeassistant
        virtualenv: /srv/homeassistant
        virtualenv_python: python3

    - name: Start homeassistant
      ansible.builtin.script:
        cmd: hass

    - name: Download of homeassistant files done
      ansible.builtin.debug:
        msg: Setup smart home via ansible playbooks
